// This file is auto-generated by @hey-api/openapi-ts

export const AnalyticsSummarySchema = {
    properties: {
        total_jobs: {
            type: 'integer',
            title: 'Total Jobs',
            default: 0
        },
        open_jobs: {
            type: 'integer',
            title: 'Open Jobs',
            default: 0
        },
        total_candidates: {
            type: 'integer',
            title: 'Total Candidates',
            default: 0
        },
        total_applications: {
            type: 'integer',
            title: 'Total Applications',
            default: 0
        },
        funnel: {
            additionalProperties: true,
            type: 'object',
            title: 'Funnel'
        },
        channels: {
            additionalProperties: true,
            type: 'object',
            title: 'Channels'
        },
        hired: {
            type: 'integer',
            title: 'Hired',
            default: 0
        },
        conversion_rate: {
            type: 'number',
            title: 'Conversion Rate',
            default: 0
        },
        pending_candidates: {
            type: 'integer',
            title: 'Pending Candidates',
            default: 0
        },
        pending_feedback: {
            type: 'integer',
            title: 'Pending Feedback',
            default: 0
        }
    },
    type: 'object',
    title: 'AnalyticsSummary'
} as const;

export const ApplicationCreateSchema = {
    properties: {
        candidate_id: {
            type: 'string',
            format: 'uuid',
            title: 'Candidate Id'
        },
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        }
    },
    type: 'object',
    required: ['candidate_id', 'job_id'],
    title: 'ApplicationCreate'
} as const;

export const ApplicationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        candidate_id: {
            type: 'string',
            format: 'uuid',
            title: 'Candidate Id'
        },
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        stage: {
            '$ref': '#/components/schemas/ApplicationStage'
        },
        source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'candidate_id', 'job_id', 'stage'],
    title: 'ApplicationPublic'
} as const;

export const ApplicationStageSchema = {
    type: 'string',
    enum: ['APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED'],
    title: 'ApplicationStage'
} as const;

export const ApplicationTransitionSchema = {
    properties: {
        target_stage: {
            '$ref': '#/components/schemas/ApplicationStage'
        }
    },
    type: 'object',
    required: ['target_stage'],
    title: 'ApplicationTransition'
} as const;

export const ApplicationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ApplicationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ApplicationsPublic'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        resource_type: {
            type: 'string',
            title: 'Resource Type'
        },
        resource_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resource Id'
        },
        before_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Before Data'
        },
        after_data: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'After Data'
        },
        ip: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'action', 'resource_type'],
    title: 'AuditLogPublic'
} as const;

export const AuditLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditLogsPublic'
} as const;

export const BatchAdvanceSchema = {
    properties: {
        application_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Application Ids'
        },
        target_stage: {
            '$ref': '#/components/schemas/ApplicationStage'
        }
    },
    type: 'object',
    required: ['application_ids', 'target_stage'],
    title: 'BatchAdvance'
} as const;

export const BatchInterviewCreateSchema = {
    properties: {
        application_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Application Ids'
        },
        interviewer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Interviewer Id'
        },
        round: {
            type: 'integer',
            minimum: 1,
            title: 'Round',
            default: 1
        },
        scheduled_time: {
            type: 'string',
            format: 'date-time',
            title: 'Scheduled Time'
        },
        interval_minutes: {
            type: 'integer',
            minimum: 1,
            title: 'Interval Minutes',
            default: 60
        }
    },
    type: 'object',
    required: ['application_ids', 'interviewer_id', 'scheduled_time'],
    title: 'BatchInterviewCreate',
    description: `§16 batch invite: schedule one interview per selected application.

Interviews are spaced \`interval_minutes\` apart starting from
\`scheduled_time\` so a single interviewer gets back-to-back slots without
tripping the ±30 min conflict check.`
} as const;

export const BatchInterviewErrorSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        detail: {
            type: 'string',
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['application_id', 'detail'],
    title: 'BatchInterviewError'
} as const;

export const BatchInterviewResultSchema = {
    properties: {
        created: {
            items: {
                '$ref': '#/components/schemas/InterviewPublic'
            },
            type: 'array',
            title: 'Created'
        },
        errors: {
            items: {
                '$ref': '#/components/schemas/BatchInterviewError'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    title: 'BatchInterviewResult'
} as const;

export const BatchNotifySchema = {
    properties: {
        application_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Application Ids'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['application_ids', 'message'],
    title: 'BatchNotify',
    description: "§16 batch notify: send an in-app message to each application's owner."
} as const;

export const BatchNotifyResultSchema = {
    properties: {
        notified: {
            type: 'integer',
            title: 'Notified',
            default: 0
        },
        skipped: {
            type: 'integer',
            title: 'Skipped',
            default: 0
        }
    },
    type: 'object',
    title: 'BatchNotifyResult'
} as const;

export const Body_admin_auth_loginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_admin-auth-login'
} as const;

export const Body_admin_candidates_upload_resumeSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_admin-candidates-upload_resume'
} as const;

export const CandidateCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        resume_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Url'
        }
    },
    type: 'object',
    required: ['name', 'email'],
    title: 'CandidateCreate'
} as const;

export const CandidatePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        resume_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'email', 'id'],
    title: 'CandidatePublic'
} as const;

export const CandidateUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        resume_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Url'
        }
    },
    type: 'object',
    title: 'CandidateUpdate'
} as const;

export const CandidatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CandidatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CandidatesPublic'
} as const;

export const FeedbackCreateSchema = {
    properties: {
        score: {
            type: 'integer',
            maximum: 100,
            minimum: 0,
            title: 'Score'
        },
        recommend: {
            type: 'boolean',
            title: 'Recommend'
        },
        comment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        }
    },
    type: 'object',
    required: ['score', 'recommend'],
    title: 'FeedbackCreate'
} as const;

export const FeedbackPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        interview_id: {
            type: 'string',
            format: 'uuid',
            title: 'Interview Id'
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        recommend: {
            type: 'boolean',
            title: 'Recommend'
        },
        comment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'interview_id', 'score', 'recommend'],
    title: 'FeedbackPublic'
} as const;

export const FileUrlSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'FileUrl',
    description: 'Resolved download URL for a stored file (resume, attachment).'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InterviewCreateSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        interviewer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Interviewer Id'
        },
        round: {
            type: 'integer',
            minimum: 1,
            title: 'Round',
            default: 1
        },
        scheduled_time: {
            type: 'string',
            format: 'date-time',
            title: 'Scheduled Time'
        }
    },
    type: 'object',
    required: ['application_id', 'interviewer_id', 'scheduled_time'],
    title: 'InterviewCreate'
} as const;

export const InterviewPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        interviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interviewer Id'
        },
        round: {
            type: 'integer',
            title: 'Round'
        },
        scheduled_time: {
            type: 'string',
            format: 'date-time',
            title: 'Scheduled Time'
        },
        status: {
            '$ref': '#/components/schemas/InterviewStatus'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        candidate_name: {
            type: 'string',
            title: 'Candidate Name',
            default: ''
        },
        job_title: {
            type: 'string',
            title: 'Job Title',
            default: ''
        },
        job_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Job Id'
        }
    },
    type: 'object',
    required: ['id', 'application_id', 'round', 'scheduled_time', 'status'],
    title: 'InterviewPublic'
} as const;

export const InterviewStatusSchema = {
    type: 'string',
    enum: ['SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'REJECTED'],
    title: 'InterviewStatus'
} as const;

export const InterviewUpdateSchema = {
    properties: {
        interviewer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interviewer Id'
        },
        round: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Round'
        },
        scheduled_time: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Scheduled Time'
        }
    },
    type: 'object',
    title: 'InterviewUpdate'
} as const;

export const InterviewsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/InterviewPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'InterviewsPublic'
} as const;

export const JobCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        headcount: {
            type: 'integer',
            minimum: 1,
            title: 'Headcount',
            default: 1
        },
        salary_min: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary Min'
        },
        salary_max: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary Max'
        },
        location: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        requirements: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requirements'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'JobCreate'
} as const;

export const JobPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        headcount: {
            type: 'integer',
            minimum: 1,
            title: 'Headcount',
            default: 1
        },
        salary_min: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary Min'
        },
        salary_max: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary Max'
        },
        location: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        requirements: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requirements'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            '$ref': '#/components/schemas/JobStatus'
        },
        creator_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creator Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'status'],
    title: 'JobPublic'
} as const;

export const JobStatusSchema = {
    type: 'string',
    enum: ['DRAFT', 'PENDING_APPROVAL', 'OPEN', 'PAUSED', 'CLOSED'],
    title: 'JobStatus'
} as const;

export const JobUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        headcount: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headcount'
        },
        salary_min: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary Min'
        },
        salary_max: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary Max'
        },
        location: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        requirements: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Requirements'
        }
    },
    type: 'object',
    title: 'JobUpdate'
} as const;

export const JobsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/JobPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'JobsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NotificationPublicSchema = {
    properties: {
        type: {
            type: 'string',
            maxLength: 64,
            title: 'Type'
        },
        content: {
            type: 'string',
            maxLength: 500,
            title: 'Content'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        read_status: {
            type: 'boolean',
            title: 'Read Status'
        },
        related_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Related Type'
        },
        related_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Related Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['type', 'content', 'id', 'user_id', 'read_status'],
    title: 'NotificationPublic'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'NotificationsPublic'
} as const;

export const OfferCreateSchema = {
    properties: {
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        salary: {
            type: 'integer',
            minimum: 0,
            title: 'Salary'
        }
    },
    type: 'object',
    required: ['application_id', 'salary'],
    title: 'OfferCreate'
} as const;

export const OfferPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        application_id: {
            type: 'string',
            format: 'uuid',
            title: 'Application Id'
        },
        salary: {
            type: 'integer',
            title: 'Salary'
        },
        status: {
            '$ref': '#/components/schemas/OfferStatus'
        },
        creator_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Creator Id'
        },
        approved_by: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Approved By'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'application_id', 'salary', 'status'],
    title: 'OfferPublic'
} as const;

export const OfferStatusSchema = {
    type: 'string',
    enum: ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'ACCEPTED', 'REJECTED'],
    title: 'OfferStatus'
} as const;

export const OfferUpdateSchema = {
    properties: {
        salary: {
            type: 'integer',
            minimum: 0,
            title: 'Salary'
        }
    },
    type: 'object',
    required: ['salary'],
    title: 'OfferUpdate'
} as const;

export const OffersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/OfferPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'OffersPublic'
} as const;

export const PortalApplicationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        job_title: {
            type: 'string',
            title: 'Job Title'
        },
        stage: {
            '$ref': '#/components/schemas/ApplicationStage'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'job_id', 'job_title', 'stage'],
    title: 'PortalApplicationPublic'
} as const;

export const PortalApplicationSubmitSchema = {
    properties: {
        job_id: {
            type: 'string',
            format: 'uuid',
            title: 'Job Id'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        resume_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Url'
        },
        source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source'
        }
    },
    type: 'object',
    required: ['job_id', 'name', 'email'],
    title: 'PortalApplicationSubmit'
} as const;

export const PortalProfileSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        resume_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resume Url'
        }
    },
    type: 'object',
    required: ['name', 'email'],
    title: 'PortalProfile',
    description: "The candidate's own profile, as seen from the portal."
} as const;

export const PortalProfileUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'PortalProfileUpdate',
    description: 'Editable profile fields. Email is the login identity -> read-only.'
} as const;

export const PortalTokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'PortalToken'
} as const;

export const RefreshTokenRequestSchema = {
    properties: {
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        }
    },
    type: 'object',
    required: ['refresh_token'],
    title: 'RefreshTokenRequest'
} as const;

export const SendCodeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'SendCodeRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        role_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Role Codes'
        }
    },
    type: 'object',
    required: ['email', 'name', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'name', 'id'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        department_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Department Id'
        },
        role_codes: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role Codes'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VerifyCodeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        code: {
            type: 'string',
            maxLength: 16,
            minLength: 4,
            title: 'Code'
        }
    },
    type: 'object',
    required: ['email', 'code'],
    title: 'VerifyCodeRequest'
} as const;