// This file is auto-generated by @hey-api/openapi-ts

export type AnalyticsSummary = {
    total_jobs?: number;
    open_jobs?: number;
    total_candidates?: number;
    total_applications?: number;
    funnel?: {
        [key: string]: unknown;
    };
    channels?: {
        [key: string]: unknown;
    };
    hired?: number;
    conversion_rate?: number;
};

export type ApplicationCreate = {
    candidate_id: string;
    job_id: string;
    source?: (string | null);
};

export type ApplicationPublic = {
    id: string;
    candidate_id: string;
    job_id: string;
    stage: ApplicationStage;
    source?: (string | null);
    owner_id?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ApplicationsPublic = {
    data: Array<ApplicationPublic>;
    count: number;
};

export type ApplicationStage = 'APPLIED' | 'SCREENING' | 'INTERVIEW' | 'OFFER' | 'HIRED' | 'REJECTED';

export type ApplicationTransition = {
    target_stage: ApplicationStage;
};

export type AuditLogPublic = {
    id: string;
    user_id?: (string | null);
    action: string;
    resource_type: string;
    resource_id?: (string | null);
    before_data?: ({
    [key: string]: unknown;
} | null);
    after_data?: ({
    [key: string]: unknown;
} | null);
    ip?: (string | null);
    created_at?: (string | null);
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type BatchAdvance = {
    application_ids: Array<(string)>;
    target_stage: ApplicationStage;
};

export type Body_admin_auth_login = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_admin_candidates_upload_resume = {
    file: string;
};

export type CandidateCreate = {
    name: string;
    email: string;
    phone?: (string | null);
    source?: (string | null);
    tags?: Array<(string)>;
    resume_url?: (string | null);
};

export type CandidatePublic = {
    name: string;
    email: string;
    phone?: (string | null);
    source?: (string | null);
    id: string;
    tags?: Array<(string)>;
    resume_url?: (string | null);
    created_at?: (string | null);
};

export type CandidatesPublic = {
    data: Array<CandidatePublic>;
    count: number;
};

export type CandidateUpdate = {
    name?: (string | null);
    email?: (string | null);
    phone?: (string | null);
    source?: (string | null);
    tags?: (Array<(string)> | null);
    resume_url?: (string | null);
};

export type FeedbackCreate = {
    score: number;
    recommend: boolean;
    comment?: (string | null);
};

export type FeedbackPublic = {
    id: string;
    interview_id: string;
    score: number;
    recommend: boolean;
    comment?: (string | null);
    created_at?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InterviewCreate = {
    application_id: string;
    interviewer_id: string;
    round?: number;
    scheduled_time: string;
};

export type InterviewPublic = {
    id: string;
    application_id: string;
    interviewer_id?: (string | null);
    round: number;
    scheduled_time: string;
    status: InterviewStatus;
    created_at?: (string | null);
};

export type InterviewsPublic = {
    data: Array<InterviewPublic>;
    count: number;
};

export type InterviewStatus = 'SCHEDULED' | 'COMPLETED' | 'CANCELLED' | 'NO_SHOW';

export type JobCreate = {
    title: string;
    department_id?: (string | null);
    headcount?: number;
    salary_min?: (number | null);
    salary_max?: (number | null);
    location?: (string | null);
    description?: (string | null);
    requirements?: (string | null);
};

export type JobPublic = {
    title: string;
    department_id?: (string | null);
    headcount?: number;
    salary_min?: (number | null);
    salary_max?: (number | null);
    location?: (string | null);
    description?: (string | null);
    requirements?: (string | null);
    id: string;
    status: JobStatus;
    creator_id?: (string | null);
    created_at?: (string | null);
};

export type JobsPublic = {
    data: Array<JobPublic>;
    count: number;
};

export type JobStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'OPEN' | 'PAUSED' | 'CLOSED';

export type JobUpdate = {
    title?: (string | null);
    department_id?: (string | null);
    headcount?: (number | null);
    salary_min?: (number | null);
    salary_max?: (number | null);
    location?: (string | null);
    description?: (string | null);
    requirements?: (string | null);
};

export type Message = {
    message: string;
};

export type NotificationPublic = {
    type: string;
    content: string;
    id: string;
    user_id: string;
    read_status: boolean;
    related_type?: (string | null);
    related_id?: (string | null);
    created_at?: (string | null);
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
};

export type OfferCreate = {
    application_id: string;
    salary: number;
};

export type OfferPublic = {
    id: string;
    application_id: string;
    salary: number;
    status: OfferStatus;
    creator_id?: (string | null);
    approved_by?: (string | null);
    created_at?: (string | null);
};

export type OffersPublic = {
    data: Array<OfferPublic>;
    count: number;
};

export type OfferStatus = 'DRAFT' | 'PENDING_APPROVAL' | 'APPROVED' | 'SENT' | 'ACCEPTED' | 'REJECTED';

export type OfferUpdate = {
    salary: number;
};

export type PortalApplicationPublic = {
    id: string;
    job_id: string;
    job_title: string;
    stage: ApplicationStage;
    created_at?: (string | null);
};

export type PortalApplicationSubmit = {
    job_id: string;
    name: string;
    email: string;
    phone?: (string | null);
    resume_url?: (string | null);
    source?: (string | null);
};

export type PortalToken = {
    access_token: string;
    token_type?: string;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type SendCodeRequest = {
    email: string;
};

export type Token = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    name: string;
    is_active?: boolean;
    password: string;
    department_id?: (string | null);
    role_codes?: Array<(string)>;
};

export type UserPublic = {
    email: string;
    name: string;
    is_active?: boolean;
    id: string;
    department_id?: (string | null);
    roles?: Array<(string)>;
    created_at?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    name?: (string | null);
    is_active?: (boolean | null);
    department_id?: (string | null);
    role_codes?: (Array<(string)> | null);
};

export type UserUpdateMe = {
    name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VerifyCodeRequest = {
    email: string;
    code: string;
};

export type AdminAnalyticsGetSummaryResponse = (AnalyticsSummary);

export type AdminApplicationsBatchAdvanceData = {
    requestBody: BatchAdvance;
};

export type AdminApplicationsBatchAdvanceResponse = (ApplicationsPublic);

export type AdminApplicationsCreateApplicationData = {
    requestBody: ApplicationCreate;
};

export type AdminApplicationsCreateApplicationResponse = (ApplicationPublic);

export type AdminApplicationsListApplicationsData = {
    jobId?: (string | null);
    limit?: number;
    skip?: number;
    stage?: (ApplicationStage | null);
};

export type AdminApplicationsListApplicationsResponse = (ApplicationsPublic);

export type AdminApplicationsGetApplicationData = {
    applicationId: string;
};

export type AdminApplicationsGetApplicationResponse = (ApplicationPublic);

export type AdminApplicationsAdvanceApplicationData = {
    applicationId: string;
    requestBody: ApplicationTransition;
};

export type AdminApplicationsAdvanceApplicationResponse = (ApplicationPublic);

export type AdminApplicationsRejectApplicationData = {
    applicationId: string;
};

export type AdminApplicationsRejectApplicationResponse = (ApplicationPublic);

export type AdminApplicationsRestoreApplicationData = {
    applicationId: string;
};

export type AdminApplicationsRestoreApplicationResponse = (ApplicationPublic);

export type AdminAuditLogsListAuditLogsData = {
    limit?: number;
    resourceType?: (string | null);
    skip?: number;
};

export type AdminAuditLogsListAuditLogsResponse = (AuditLogsPublic);

export type AdminAuthLoginData = {
    formData: Body_admin_auth_login;
};

export type AdminAuthLoginResponse = (Token);

export type AdminAuthRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type AdminAuthRefreshTokenResponse = (Token);

export type AdminCandidatesListCandidatesData = {
    keyword?: (string | null);
    limit?: number;
    skip?: number;
    source?: (string | null);
    tag?: (string | null);
};

export type AdminCandidatesListCandidatesResponse = (CandidatesPublic);

export type AdminCandidatesCreateCandidateData = {
    requestBody: CandidateCreate;
};

export type AdminCandidatesCreateCandidateResponse = (CandidatePublic);

export type AdminCandidatesGetCandidateData = {
    candidateId: string;
};

export type AdminCandidatesGetCandidateResponse = (CandidatePublic);

export type AdminCandidatesUpdateCandidateData = {
    candidateId: string;
    requestBody: CandidateUpdate;
};

export type AdminCandidatesUpdateCandidateResponse = (CandidatePublic);

export type AdminCandidatesUploadResumeData = {
    candidateId: string;
    formData: Body_admin_candidates_upload_resume;
};

export type AdminCandidatesUploadResumeResponse = (CandidatePublic);

export type AdminInterviewsListCalendarResponse = (Array<InterviewPublic>);

export type AdminInterviewsListInterviewsData = {
    limit?: number;
    skip?: number;
    status?: (InterviewStatus | null);
};

export type AdminInterviewsListInterviewsResponse = (InterviewsPublic);

export type AdminInterviewsCreateInterviewData = {
    requestBody: InterviewCreate;
};

export type AdminInterviewsCreateInterviewResponse = (InterviewPublic);

export type AdminInterviewsGetInterviewData = {
    interviewId: string;
};

export type AdminInterviewsGetInterviewResponse = (InterviewPublic);

export type AdminInterviewsGetFeedbackData = {
    interviewId: string;
};

export type AdminInterviewsGetFeedbackResponse = (FeedbackPublic);

export type AdminInterviewsSubmitFeedbackData = {
    interviewId: string;
    requestBody: FeedbackCreate;
};

export type AdminInterviewsSubmitFeedbackResponse = (FeedbackPublic);

export type AdminInterviewsCancelInterviewData = {
    interviewId: string;
};

export type AdminInterviewsCancelInterviewResponse = (InterviewPublic);

export type AdminJobsListJobsData = {
    keyword?: (string | null);
    limit?: number;
    skip?: number;
    status?: (JobStatus | null);
};

export type AdminJobsListJobsResponse = (JobsPublic);

export type AdminJobsCreateJobData = {
    requestBody: JobCreate;
};

export type AdminJobsCreateJobResponse = (JobPublic);

export type AdminJobsGetJobData = {
    jobId: string;
};

export type AdminJobsGetJobResponse = (JobPublic);

export type AdminJobsUpdateJobData = {
    jobId: string;
    requestBody: JobUpdate;
};

export type AdminJobsUpdateJobResponse = (JobPublic);

export type AdminJobsDeleteJobData = {
    jobId: string;
};

export type AdminJobsDeleteJobResponse = (Message);

export type AdminJobsPublishJobData = {
    jobId: string;
};

export type AdminJobsPublishJobResponse = (JobPublic);

export type AdminJobsCloseJobData = {
    jobId: string;
};

export type AdminJobsCloseJobResponse = (JobPublic);

export type AdminJobsReopenJobData = {
    jobId: string;
};

export type AdminJobsReopenJobResponse = (JobPublic);

export type AdminNotificationsListNotificationsData = {
    limit?: number;
    skip?: number;
    unreadOnly?: boolean;
};

export type AdminNotificationsListNotificationsResponse = (NotificationsPublic);

export type AdminNotificationsMarkReadData = {
    notificationId: string;
};

export type AdminNotificationsMarkReadResponse = (NotificationPublic);

export type AdminNotificationsMarkAllReadResponse = (Message);

export type AdminOffersListOffersData = {
    limit?: number;
    skip?: number;
};

export type AdminOffersListOffersResponse = (OffersPublic);

export type AdminOffersCreateOfferData = {
    requestBody: OfferCreate;
};

export type AdminOffersCreateOfferResponse = (OfferPublic);

export type AdminOffersGetOfferData = {
    offerId: string;
};

export type AdminOffersGetOfferResponse = (OfferPublic);

export type AdminOffersUpdateOfferData = {
    offerId: string;
    requestBody: OfferUpdate;
};

export type AdminOffersUpdateOfferResponse = (OfferPublic);

export type AdminOffersSubmitOfferData = {
    offerId: string;
};

export type AdminOffersSubmitOfferResponse = (OfferPublic);

export type AdminOffersApproveOfferData = {
    offerId: string;
};

export type AdminOffersApproveOfferResponse = (OfferPublic);

export type AdminOffersSendOfferData = {
    offerId: string;
};

export type AdminOffersSendOfferResponse = (OfferPublic);

export type AdminOffersCancelOfferData = {
    offerId: string;
};

export type AdminOffersCancelOfferResponse = (OfferPublic);

export type AdminUsersReadUserMeResponse = (UserPublic);

export type AdminUsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type AdminUsersUpdateUserMeResponse = (UserPublic);

export type AdminUsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type AdminUsersUpdatePasswordMeResponse = (Message);

export type AdminUsersListUsersData = {
    limit?: number;
    skip?: number;
};

export type AdminUsersListUsersResponse = (UsersPublic);

export type AdminUsersCreateUserData = {
    requestBody: UserCreate;
};

export type AdminUsersCreateUserResponse = (UserPublic);

export type AdminUsersGetUserData = {
    userId: string;
};

export type AdminUsersGetUserResponse = (UserPublic);

export type AdminUsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type AdminUsersUpdateUserResponse = (UserPublic);

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type PortalApplicationsListMyApplicationsResponse = (Array<PortalApplicationPublic>);

export type PortalApplicationsSubmitApplicationData = {
    requestBody: PortalApplicationSubmit;
};

export type PortalApplicationsSubmitApplicationResponse = (PortalApplicationPublic);

export type PortalApplicationsGetMyApplicationData = {
    applicationId: string;
};

export type PortalApplicationsGetMyApplicationResponse = (PortalApplicationPublic);

export type PortalAuthSendCodeData = {
    requestBody: SendCodeRequest;
};

export type PortalAuthSendCodeResponse = (Message);

export type PortalAuthVerifyCodeData = {
    requestBody: VerifyCodeRequest;
};

export type PortalAuthVerifyCodeResponse = (PortalToken);

export type PortalJobsListPortalJobsData = {
    keyword?: (string | null);
    limit?: number;
    skip?: number;
};

export type PortalJobsListPortalJobsResponse = (JobsPublic);

export type PortalJobsGetPortalJobData = {
    jobId: string;
};

export type PortalJobsGetPortalJobResponse = (JobPublic);

export type PortalOffersListMyOffersResponse = (Array<OfferPublic>);

export type PortalOffersGetMyOfferData = {
    offerId: string;
};

export type PortalOffersGetMyOfferResponse = (OfferPublic);

export type PortalOffersAcceptOfferData = {
    offerId: string;
};

export type PortalOffersAcceptOfferResponse = (OfferPublic);

export type PortalOffersRejectOfferData = {
    offerId: string;
};

export type PortalOffersRejectOfferResponse = (OfferPublic);