/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalLoginRouteImport } from './routes/portal/login'
import { Route as PortalApplicationsRouteImport } from './routes/portal/applications'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutOffersRouteImport } from './routes/_layout/offers'
import { Route as LayoutJobsRouteImport } from './routes/_layout/jobs'
import { Route as LayoutInterviewsRouteImport } from './routes/_layout/interviews'
import { Route as LayoutCandidatesRouteImport } from './routes/_layout/candidates'
import { Route as LayoutBoardRouteImport } from './routes/_layout/board'
import { Route as LayoutAuditLogsRouteImport } from './routes/_layout/audit-logs'
import { Route as LayoutAnalyticsRouteImport } from './routes/_layout/analytics'
import { Route as PortalJobsIdRouteImport } from './routes/portal/jobs/$id'
import { Route as LayoutJobsIdRouteImport } from './routes/_layout/jobs/$id'
import { Route as LayoutCandidatesIdRouteImport } from './routes/_layout/candidates/$id'
import { Route as LayoutApplicationsIdRouteImport } from './routes/_layout/applications/$id'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationsRoute = PortalApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => PortalRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOffersRoute = LayoutOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobsRoute = LayoutJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutInterviewsRoute = LayoutInterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCandidatesRoute = LayoutCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBoardRoute = LayoutBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuditLogsRoute = LayoutAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyticsRoute = LayoutAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => LayoutRoute,
} as any)
const PortalJobsIdRoute = PortalJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => PortalRoute,
} as any)
const LayoutJobsIdRoute = LayoutJobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutJobsRoute,
} as any)
const LayoutCandidatesIdRoute = LayoutCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutCandidatesRoute,
} as any)
const LayoutApplicationsIdRoute = LayoutApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/analytics': typeof LayoutAnalyticsRoute
  '/audit-logs': typeof LayoutAuditLogsRoute
  '/board': typeof LayoutBoardRoute
  '/candidates': typeof LayoutCandidatesRouteWithChildren
  '/interviews': typeof LayoutInterviewsRoute
  '/jobs': typeof LayoutJobsRouteWithChildren
  '/offers': typeof LayoutOffersRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/': typeof PortalIndexRoute
  '/applications/$id': typeof LayoutApplicationsIdRoute
  '/candidates/$id': typeof LayoutCandidatesIdRoute
  '/jobs/$id': typeof LayoutJobsIdRoute
  '/portal/jobs/$id': typeof PortalJobsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof LayoutAnalyticsRoute
  '/audit-logs': typeof LayoutAuditLogsRoute
  '/board': typeof LayoutBoardRoute
  '/candidates': typeof LayoutCandidatesRouteWithChildren
  '/interviews': typeof LayoutInterviewsRoute
  '/jobs': typeof LayoutJobsRouteWithChildren
  '/offers': typeof LayoutOffersRoute
  '/settings': typeof LayoutSettingsRoute
  '/users': typeof LayoutUsersRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/': typeof LayoutIndexRoute
  '/portal': typeof PortalIndexRoute
  '/applications/$id': typeof LayoutApplicationsIdRoute
  '/candidates/$id': typeof LayoutCandidatesIdRoute
  '/jobs/$id': typeof LayoutJobsIdRoute
  '/portal/jobs/$id': typeof PortalJobsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/_layout/analytics': typeof LayoutAnalyticsRoute
  '/_layout/audit-logs': typeof LayoutAuditLogsRoute
  '/_layout/board': typeof LayoutBoardRoute
  '/_layout/candidates': typeof LayoutCandidatesRouteWithChildren
  '/_layout/interviews': typeof LayoutInterviewsRoute
  '/_layout/jobs': typeof LayoutJobsRouteWithChildren
  '/_layout/offers': typeof LayoutOffersRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/portal/applications': typeof PortalApplicationsRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/profile': typeof PortalProfileRoute
  '/_layout/': typeof LayoutIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_layout/applications/$id': typeof LayoutApplicationsIdRoute
  '/_layout/candidates/$id': typeof LayoutCandidatesIdRoute
  '/_layout/jobs/$id': typeof LayoutJobsIdRoute
  '/portal/jobs/$id': typeof PortalJobsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/analytics'
    | '/audit-logs'
    | '/board'
    | '/candidates'
    | '/interviews'
    | '/jobs'
    | '/offers'
    | '/settings'
    | '/users'
    | '/portal/applications'
    | '/portal/login'
    | '/portal/profile'
    | '/portal/'
    | '/applications/$id'
    | '/candidates/$id'
    | '/jobs/$id'
    | '/portal/jobs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/audit-logs'
    | '/board'
    | '/candidates'
    | '/interviews'
    | '/jobs'
    | '/offers'
    | '/settings'
    | '/users'
    | '/portal/applications'
    | '/portal/login'
    | '/portal/profile'
    | '/'
    | '/portal'
    | '/applications/$id'
    | '/candidates/$id'
    | '/jobs/$id'
    | '/portal/jobs/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/portal'
    | '/_layout/analytics'
    | '/_layout/audit-logs'
    | '/_layout/board'
    | '/_layout/candidates'
    | '/_layout/interviews'
    | '/_layout/jobs'
    | '/_layout/offers'
    | '/_layout/settings'
    | '/_layout/users'
    | '/portal/applications'
    | '/portal/login'
    | '/portal/profile'
    | '/_layout/'
    | '/portal/'
    | '/_layout/applications/$id'
    | '/_layout/candidates/$id'
    | '/_layout/jobs/$id'
    | '/portal/jobs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/applications': {
      id: '/portal/applications'
      path: '/applications'
      fullPath: '/portal/applications'
      preLoaderRoute: typeof PortalApplicationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/offers': {
      id: '/_layout/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof LayoutOffersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jobs': {
      id: '/_layout/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof LayoutJobsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/interviews': {
      id: '/_layout/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof LayoutInterviewsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/candidates': {
      id: '/_layout/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof LayoutCandidatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/board': {
      id: '/_layout/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof LayoutBoardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/audit-logs': {
      id: '/_layout/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof LayoutAuditLogsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analytics': {
      id: '/_layout/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof LayoutAnalyticsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/portal/jobs/$id': {
      id: '/portal/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/portal/jobs/$id'
      preLoaderRoute: typeof PortalJobsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_layout/jobs/$id': {
      id: '/_layout/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof LayoutJobsIdRouteImport
      parentRoute: typeof LayoutJobsRoute
    }
    '/_layout/candidates/$id': {
      id: '/_layout/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof LayoutCandidatesIdRouteImport
      parentRoute: typeof LayoutCandidatesRoute
    }
    '/_layout/applications/$id': {
      id: '/_layout/applications/$id'
      path: '/applications/$id'
      fullPath: '/applications/$id'
      preLoaderRoute: typeof LayoutApplicationsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutCandidatesRouteChildren {
  LayoutCandidatesIdRoute: typeof LayoutCandidatesIdRoute
}

const LayoutCandidatesRouteChildren: LayoutCandidatesRouteChildren = {
  LayoutCandidatesIdRoute: LayoutCandidatesIdRoute,
}

const LayoutCandidatesRouteWithChildren =
  LayoutCandidatesRoute._addFileChildren(LayoutCandidatesRouteChildren)

interface LayoutJobsRouteChildren {
  LayoutJobsIdRoute: typeof LayoutJobsIdRoute
}

const LayoutJobsRouteChildren: LayoutJobsRouteChildren = {
  LayoutJobsIdRoute: LayoutJobsIdRoute,
}

const LayoutJobsRouteWithChildren = LayoutJobsRoute._addFileChildren(
  LayoutJobsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAnalyticsRoute: typeof LayoutAnalyticsRoute
  LayoutAuditLogsRoute: typeof LayoutAuditLogsRoute
  LayoutBoardRoute: typeof LayoutBoardRoute
  LayoutCandidatesRoute: typeof LayoutCandidatesRouteWithChildren
  LayoutInterviewsRoute: typeof LayoutInterviewsRoute
  LayoutJobsRoute: typeof LayoutJobsRouteWithChildren
  LayoutOffersRoute: typeof LayoutOffersRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutApplicationsIdRoute: typeof LayoutApplicationsIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalyticsRoute: LayoutAnalyticsRoute,
  LayoutAuditLogsRoute: LayoutAuditLogsRoute,
  LayoutBoardRoute: LayoutBoardRoute,
  LayoutCandidatesRoute: LayoutCandidatesRouteWithChildren,
  LayoutInterviewsRoute: LayoutInterviewsRoute,
  LayoutJobsRoute: LayoutJobsRouteWithChildren,
  LayoutOffersRoute: LayoutOffersRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutApplicationsIdRoute: LayoutApplicationsIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface PortalRouteChildren {
  PortalApplicationsRoute: typeof PortalApplicationsRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalJobsIdRoute: typeof PortalJobsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApplicationsRoute: PortalApplicationsRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalJobsIdRoute: PortalJobsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
